### PR TITLE
Switch json library from poison to jason

### PR DESCRIPTION
**Pull request by indocomsoft**
`jason` is a json library that is faster than `poison`, and currently most of the ecosystem is switching to it (including `phoenix` and `ecto`).

More information at https://elixirforum.com/t/announcing-jason-a-blazing-fast-json-parser-and-generator-in-pure-elixir/11030

### CODE REVIEW

**Comment by rockneurotiko** [comment]
I'm going to make the JSON encoding/decoding backend configurable, but by default it will use Jason

**Comment by indocomsoft** [comment]
I see. Glad to know that it's on the roadmap!

Feel free to close this then.

**Comment by rockneurotiko** [comment]
Ey @indocomsoft can you check the PR #15 that adds the json engine configuration? 😄

**Comment by rockneurotiko** [comment]
Closing in favor or #15

**Pull request closed without merging**
