### PR TITLE
Expose function to convert method responses to models

### PR DESCRIPTION
**Pull request by jfpedroza**
I want to store messages as JSON in a database and then be able to convert the JSON back to the Message struct for easier  usage.

Instead of duplicating the logic, I thought it was best to make the function public. It also has the benefit of allowing us to use it for webhook updates. It was a suprise when switching from polling to webhooks that the values of the update weren't structs.

I'm not completely sold on the name, so let me know if you want me to change it to something else.

### CODE REVIEW

**Comment by rockneurotiko** [comment]
Oh, that's actually a good idea, and the problem of webhook messages not having inner structs it was a real problem that I haven't seen!

I'm not the best one in namings, I'm thinking on alternatives for `cast` but nothing comes to my mind, so let's go with Cast

I'm going to merge the PR, do you need a release or can I delay it?

**Review by rockneurotiko — APPROVED** [review]
Awesome! 🎉 🧡

**Comment by jfpedroza** [comment]
That was fast 🚀.

I don't need a release immediately. I can point to the repo directly. 👌🏽

**Comment by rockneurotiko** [comment]
Thanks for the contribution!

I'll release soon anyway, mainly for the bug of webhooks not decoding correctly

**Comment by rockneurotiko** [comment]
Sorry for the delay! I just released the version `0.54.0` with your PR and another fix 😄

**Comment by jfpedroza** [comment]
Thanks!

**Pull request merged**
